version: '3.4'

services:
  traning.microservices.catalog:
    image: ${DOCKER_REGISTRY-}traning.microservices.catalog
    build:
      context: .
      dockerfile: Traning.AspNetCore.Microservices.Catalog.API/Dockerfile
  traning.microservices.jaeger:
    image: jaegertracing/all-in-one:latest
